//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\LBT\Dropbox\Instrumentacion y control\ProyectoFinal\test\run.py
///  Source class: MiDriver
///  Generation timestamp: 2019-06-25T19:04:26.499535
///  Class code hash: fe638ac00be86e572132174a355b423f3879b3b8
///
/////////////////////////////////////////////////////////////

#include <arduino.h>

#include "inodriver_user.h"

// variables MOTOR:
int pin_motor = 10;
int pin_laser = 9;
float val;

void user_setup() {
  pinMode(pin_motor,OUTPUT);
  pinMode(pin_laser,OUTPUT);
}

void user_loop() {
  int set_LASER(float);
}

// COMMAND: MOTOR, FEAT: motor
int set_MOTOR(float istep) {
  digitalWrite(pin_motor , HIGH);
  delay(100);
  digitalWrite(pin_motor , LOW);
  delay(100);
  return 0;
};

// COMMAND: DIODO, FEAT: pow_diodo
float get_DIODO() {
  val = analogRead(A0);
  return val;
};

// COMMAND: LASER, FEAT: pow_laser
int set_LASER(float value) {
  analogWrite(pin_laser, value); 
  delay(1000);    
  return 0;
};
