//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\LBT\Dropbox\Instrumentacion y control\ProyectoFinal\test\run.py
///  Source class: MiDriver
///  Generation timestamp: 2019-06-25T19:04:26.499535
///  Class code hash: fe638ac00be86e572132174a355b423f3879b3b8
///
/////////////////////////////////////////////////////////////

#include "inodriver_user.h"
// variables MOTOR:
int pin_motor = 10;
int istep = 0;
float val;

void user_setup() {
  Serial.begin(9600);
  pinMode(pin_motor,OUTPUT);
  analogReadResolution(8);
  Serial.setTimeout(50);
}

void user_loop() {
}

// COMMAND: MOTOR, FEAT: motor
int set_MOTOR(float istep) {
  if (istep>0) {
    Serial.println(istep);
    //digitalWrite(pin_motor , LOW);
    //delay(100);
    digitalWrite(pin_motor , HIGH);
    delay(100);
    digitalWrite(pin_motor , LOW);
    delay(100);
    //digitalWrite(pin_motor , HIGH);
    istep=0;
    }
  }
  return 0;
};


// COMMAND: DIODO, FEAT: pow_diodo
float get_DIODO() {
  val = analogRead(A0);
  Serial.println("VALUE:\n");
  Serial.println(val);
  return 0.0;
};


// COMMAND: LASER, FEAT: pow_laser
int set_LASER(float value) {
  return 0;
};


