//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\LBT\Dropbox\Instrumentacion y control\ProyectoFinal\test\run.py
///  Source class: MiDriver
///  Generation timestamp: 2019-06-25T19:04:26.499535
///  Class code hash: fe638ac00be86e572132174a355b423f3879b3b8
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
int set_MOTOR(float); 
float get_DIODO(); 
int set_LASER(float); 


#endif // inodriver_user_h