//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\LBT\Dropbox\Instrumentacion y control\ProyectoFinal\lantz\run.py
///  Source class: LEDDriver
///  Generation timestamp: 2019-06-25T18:10:47.920727
///  Class code hash: 8647375a3d456c77a25af7a8712a5951c71a1594
///
/////////////////////////////////////////////////////////////



#include "inodriver_user.h"

void user_setup() {
   pinMode(13, OUTPUT);
}

void user_loop() {
}
// COMMAND: LED, FEAT: led
int get_LED() {
  return 0;
};

int set_LED(int value) {
   if (value>0)
      digitalWrite(13, HIGH);
      delay(100);
   else
      digitalWrite(13, LOW);
      delay(100);
   return 0;
};