//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\LBT\Dropbox\Instrumentacion y control\ProyectoFinal\lantz\run.py
///  Source class: LEDDriver
///  Generation timestamp: 2019-06-25T18:10:47.920727
///  Class code hash: 8647375a3d456c77a25af7a8712a5951c71a1594
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
int get_LED(); 
int set_LED(int); 


#endif // inodriver_user_h