//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /home/ale/instrumentacion19/ProyectoFinal/linux_test/run.py
///  Source class: MiDriver
///  Generation timestamp: 2019-06-27T10:59:54.436011
///  Class code hash: fe638ac00be86e572132174a355b423f3879b3b8
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

void user_setup();
void user_loop();
int set_MOTOR(float); 
float get_DIODO(); 
int set_LASER(float); 


#endif // inodriver_user_h