//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /home/ale/instrumentacion19/ProyectoFinal/linux_test/run.py
///  Source class: MiDriver
///  Generation timestamp: 2019-06-27T10:59:54.436011
///  Class code hash: fe638ac00be86e572132174a355b423f3879b3b8
///
/////////////////////////////////////////////////////////////



#include "inodriver_user.h"

void user_setup() {
}

void user_loop() {
}
// COMMAND: MOTOR, FEAT: motor
int set_MOTOR(float value) {
  return 0;
};


// COMMAND: DIODO, FEAT: pow_diodo
float get_DIODO() {
  return 0.0;
};


// COMMAND: LASER, FEAT: pow_laser
int set_LASER(float value) {
  return 0;
};


